name = "SignalBase"
uuid = "00c44e92-20f5-44bc-8f45-a1dcef76ba38"
authors = ["David F. Little"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
